[package]
name = "midi_panic"
version = "0.1.0"
edition = "2024"
authors = ["Lokan Chung <lokanchung@gmail.com>"]
license = "ISC"

[lib]
crate-type = ["cdylib"]

[dependencies]
nih_plug = { path = "../nih-plug", features = ["assert_process_allocs"] }
